'use strict';

const { execSync } = require('child_process');
const { PipelineError } = require('./errors.js');

function run(command, cwd) {
  try {
    return execSync(command, {
      cwd,
      encoding: 'utf8',
      shell: true,
      stdio: 'pipe'
    }).trim();
  } catch (error) {
    throw new PipelineError('GITHUB_COMMAND_FAILED', error.message, {
      command,
      stdout: error.stdout ? String(error.stdout) : '',
      stderr: error.stderr ? String(error.stderr) : ''
    });
  }
}

function ensureGitRepo(repoPath) {
  run('git rev-parse --is-inside-work-tree', repoPath);
}

function createBranch(config, branchName, baseBranch) {
  ensureGitRepo(config.repoPath);
  const existing = run(`git branch --list ${branchName}`, config.repoPath);
  if (existing) {
    run(`git checkout ${branchName}`, config.repoPath);
  } else {
    run(`git checkout ${baseBranch}`, config.repoPath);
    run(`git checkout -b ${branchName}`, config.repoPath);
  }
  return { branch: branchName, base: baseBranch };
}

function buildPrBody(slice) {
  const criteria = slice.acceptance_criteria.map((criterion) => `- [ ] ${criterion}`).join('\n');
  const files = slice.affected_files.length ? slice.affected_files.join('\n') : 'None reported';
  const tests = slice.test_results
    ? `Passed: ${slice.test_results.passCount || 0}, Failed: ${slice.test_results.failCount || 0}`
    : 'Not run';

  return [
    `## Slice: ${slice.id} - ${slice.title}`,
    '',
    '### What this does',
    slice.description,
    '',
    '### Acceptance Criteria',
    criteria,
    '',
    '### Files Changed',
    files,
    '',
    '### Test Results',
    tests,
    '',
    '---',
    '*Generated by Pipeline System*'
  ].join('\n');
}

function openPR(config, slice, branchName) {
  ensureGitRepo(config.repoPath);
  run(`git push -u origin ${branchName}`, config.repoPath);
  const title = `${slice.id}: ${slice.title}`;
  const body = buildPrBody(slice).replace(/"/g, '\\"');
  const output = run(
    `gh pr create --title "${title.replace(/"/g, '\\"')}" --body "${body}" --base ${config.defaultBranch} --head ${branchName}`,
    config.repoPath
  );

  const numberMatch = output.match(/\/pull\/(\d+)/);
  return {
    url: output,
    number: numberMatch ? Number(numberMatch[1]) : null
  };
}

function getPRStatus(config, prNumber) {
  const raw = run(`gh pr view ${prNumber} --json number,state,closed,mergedAt,url`, config.repoPath);
  const parsed = JSON.parse(raw);
  return {
    number: parsed.number,
    state: parsed.state,
    closed: Boolean(parsed.closed),
    merged: Boolean(parsed.mergedAt),
    url: parsed.url
  };
}

module.exports = {
  createBranch,
  openPR,
  getPRStatus
};
