'use strict';

const { PipelineError } = require('./errors.js');
const { runCommand } = require('./command-runner.js');

function escapeBody(value) {
  return String(value || '').replace(/"/g, '\\"');
}

function buildPrBody(slice) {
  const criteria = slice.acceptance_criteria.map((criterion) => `- [ ] ${criterion}`).join('\n');
  const files = slice.affected_files.length ? slice.affected_files.join('\n') : 'None reported';
  const tests = slice.test_results
    ? `Passed: ${slice.test_results.passCount || 0}, Failed: ${slice.test_results.failCount || 0}`
    : 'Not run';

  return [
    `## Slice: ${slice.id} - ${slice.title}`,
    '',
    '### What this does',
    slice.description,
    '',
    '### Acceptance Criteria',
    criteria,
    '',
    '### Files Changed',
    files,
    '',
    '### Test Results',
    tests,
    '',
    '---',
    '*Generated by Pipeline System*'
  ].join('\n');
}

function createGitHubAdapter(config, gitAdapter) {
  function runGh(args, metadata = {}) {
    return runCommand(
      config,
      {
        name: `gh:${args[0]}`,
        exec: [...config.github.ghExec, ...args],
        cwd: config.repoPath,
        timeoutSeconds: config.github.timeoutSeconds,
        envAllowlist: ['GH_TOKEN', 'GITHUB_TOKEN']
      },
      metadata
    );
  }

  function ensureAuth(metadata = {}) {
    try {
      runGh(['auth', 'status'], metadata);
      return { passed: true };
    } catch (error) {
      return {
        passed: false,
        error: error.message,
        details: error.details || null
      };
    }
  }

  function openPR(slice, branchName, metadata = {}) {
    gitAdapter.pushBranch(branchName, metadata);
    const title = `${slice.id}: ${slice.title}`;
    const body = escapeBody(buildPrBody(slice));
    const output = runGh([
      'pr',
      'create',
      '--title',
      title,
      '--body',
      body,
      '--base',
      config.defaultBranch,
      '--head',
      branchName
    ], metadata);

    const numberMatch = output.stdout.match(/\/pull\/(\d+)/);
    return {
      url: output.stdout.trim(),
      number: numberMatch ? Number(numberMatch[1]) : null,
      command_run: output
    };
  }

  function getPRStatus(prNumber, metadata = {}) {
    const raw = runGh(['pr', 'view', String(prNumber), '--json', 'number,state,closed,mergedAt,url'], metadata);
    let parsed;
    try {
      parsed = JSON.parse(raw.stdout);
    } catch (error) {
      throw new PipelineError('GITHUB_BAD_JSON', 'GitHub CLI returned invalid JSON', {
        stdout: raw.stdout,
        stderr: raw.stderr
      });
    }

    return {
      number: parsed.number,
      state: parsed.state,
      closed: Boolean(parsed.closed),
      merged: Boolean(parsed.mergedAt),
      url: parsed.url,
      command_run: raw
    };
  }

  return {
    ensureAuth,
    openPR,
    getPRStatus
  };
}

module.exports = {
  buildPrBody,
  createGitHubAdapter
};
